# mapping of categories 

# Mapping of causes 
CAUSE_MAP = {
    "Infractions au Code de la route": [
        "DISREGARDING TRAFFIC SIGNALS", "DISREGARDING STOP SIGN", "DISREGARDING OTHER TRAFFIC SIGNS",
        "DISREGARDING YIELD SIGN", "TURNING RIGHT ON RED", "DISREGARDING ROAD MARKINGS",
        "PASSING STOPPED SCHOOL BUS"
    ],
    "Conduite imprudente": [
        "IMPROPER TURNING/NO SIGNAL", "IMPROPER OVERTAKING/PASSING",
        "DRIVING ON WRONG SIDE/WRONG WAY", "FAILING TO YIELD RIGHT-OF-WAY",
        "FAILING TO REDUCE SPEED TO AVOID CRASH", "EXCEEDING SAFE SPEED FOR CONDITIONS",
        "EXCEEDING AUTHORIZED SPEED LIMIT", "FOLLOWING TOO CLOSELY",
        "OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER"
    ],
    "Conduite inexpérimentée": [
        "IMPROPER BACKING", "IMPROPER LANE USAGE", "DRIVING SKILLS/KNOWLEDGE/EXPERIENCE"
    ],
    "Déficiences du conducteur": [
        "UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)",
        "HAD BEEN DRINKING (USE WHEN ARREST IS NOT MADE)", "PHYSICAL CONDITION OF DRIVER"
    ],
    "Distractions du conducteur": [
        "DISTRACTION - FROM OUTSIDE VEHICLE", "DISTRACTION - FROM INSIDE VEHICLE",
        "DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)",
        "CELL PHONE USE OTHER THAN TEXTING", "TEXTING"
    ],
    "Facteurs environnementaux et externes": [
        "VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)",
        "EVASIVE ACTION DUE TO ANIMAL, OBJECT, NONMOTORIST", "ANIMAL",
        "ROAD ENGINEERING/SURFACE/MARKING DEFECTS", "ROAD CONSTRUCTION/MAINTENANCE",
        "EQUIPMENT - VEHICLE CONDITION", "RELATED TO BUS STOP", "OBSTRUCTED CROSSWALKS"
    ],
    "Conditions météorologiques": ["WEATHER"]
}

# Mapping of weather
WEATHER_MAP = {
    "Temps clair": ["CLEAR"],
    "Pluie / Neige": ["RAIN", "FREEZING RAIN/DRIZZLE", "SNOW", "BLOWING SNOW"],
    "Temps nuageux ou brouillard": ["CLOUDY/OVERCAST", "FOG/SMOKE/HAZE"],
    "Conditions météorologiques extrêmes": ["SLEET/HAIL", "SEVERE CROSS WIND GATE", "BLOWING SAND, SOIL, DIRT", "UNKNOWN", "OTHER"]
}

# Mapping of traffic type
TRAFFIC_MAP = {
    "Routes standards": ["NOT DIVIDED", "ONE-WAY", "TRAFFIC ROUTE", "CENTER TURN LANE"],
    "Intersections et routes divisées": [
        "FOUR WAY", "T-INTERSECTION", "L-INTERSECTION", "Y-INTERSECTION",
        "FIVE POINT, OR MORE", "ROUNDABOUT", "DIVIDED - W/MEDIAN (NOT RAISED)", "DIVIDED - W/MEDIAN BARRIER"
    ],
    "Routes spéciales ou inconnues": [
        "RAMP", "DRIVEWAY", "ALLEY", "PARKING LOT", "OTHER",
        "UNKNOWN INTERSECTION TYPE", "UNKNOWN", "NOT REPORTED"
    ]
}